# Generated by Django 2.0.7 on 2018-07-18 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('privilegios', '0001_initial'),
        ('cargo', '0001_initial'),
        ('turno', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalCod', models.CharField(max_length=15, unique=True)),
                ('personalApellidos', models.CharField(max_length=60)),
                ('personalNombres', models.CharField(max_length=60)),
                ('personalGenero', models.CharField(max_length=15)),
                ('personalDni', models.CharField(max_length=8, unique=True)),
                ('personalTelefono', models.CharField(max_length=15)),
                ('personalCelular', models.CharField(max_length=15)),
                ('personalEmail', models.EmailField(max_length=50, null=True)),
                ('personalDomicilio', models.CharField(max_length=80)),
                ('personalFechaNac', models.DateField()),
                ('personalEstado', models.CharField(max_length=1)),
                ('descripcionLIC', models.CharField(max_length=9, null=True)),
                ('categoricaLIC', models.CharField(max_length=5, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargo.Cargo')),
                ('opcion', models.ManyToManyField(blank=True, to='privilegios.Opcion')),
                ('subCargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cargo.SubCargo')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turno.Turno')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
