# Generated by Django 2.0.7 on 2018-07-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudadanoCod', models.CharField(max_length=15, unique=True)),
                ('ciudadanoNombres', models.CharField(max_length=80)),
                ('ciudadanoDni', models.CharField(max_length=8)),
                ('ciudadanoEdad', models.IntegerField()),
            ],
        ),
    ]
