# Generated by Django 2.0.7 on 2018-07-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipovehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculoCod', models.CharField(max_length=15, unique=True)),
                ('vehiculoMarca', models.CharField(max_length=30)),
                ('vehiculoModelo', models.CharField(max_length=20)),
                ('vehiculoPlaca', models.CharField(max_length=20, unique=True)),
                ('vehiculoNumero', models.IntegerField(null=True)),
                ('tipovehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipovehiculo.TipoVehiculo')),
            ],
        ),
    ]
