# Generated by Django 2.0.7 on 2018-07-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcionDescripcion', models.CharField(max_length=20)),
                ('opcionRecurso', models.CharField(max_length=100)),
                ('NAPCodigo', models.CharField(max_length=1)),
                ('NOPEstado', models.CharField(max_length=1)),
                ('NOPDependencia', models.IntegerField()),
                ('opcionIcono', models.CharField(max_length=70)),
            ],
        ),
    ]
