# Generated by Django 2.0.7 on 2018-07-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipovehiculoCod', models.CharField(max_length=15, unique=True)),
                ('tipovehiculoNombre', models.CharField(max_length=40)),
            ],
        ),
    ]
