# Generated by Django 2.0.7 on 2018-07-19 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicador', '0001_initial'),
        ('vehiculo', '0001_initial'),
        ('incidencia', '0001_initial'),
        ('tipoinforme', '0001_initial'),
        ('personal', '0001_initial'),
        ('patrullaje', '0001_initial'),
        ('comisaria', '0001_initial'),
        ('turno', '0001_initial'),
        ('motivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informeCod', models.CharField(max_length=15, unique=True)),
                ('informeFecha', models.DateField()),
                ('informeAsunto', models.CharField(max_length=50)),
                ('informeObservacion', models.CharField(max_length=150, null=True)),
                ('comisaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comisaria.Comisaria')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidencia.Incidencia')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicador.Indicador')),
                ('motivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='motivo.Motivo')),
                ('patrullaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patrullaje.Patrullaje')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.Personal')),
                ('tipoinforme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoinforme.TipoInforme')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turno.Turno')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculo.Vehiculo')),
            ],
        ),
    ]
