# Generated by Django 2.0.7 on 2018-07-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidenciaCod', models.CharField(max_length=15, null=True)),
                ('incidenciaDescripcion', models.CharField(max_length=80, null=True)),
                ('incidenciaTraslado', models.CharField(max_length=2, null=True)),
                ('incidenciaMasculino', models.IntegerField(null=True)),
                ('incidenciaFemenino', models.IntegerField(null=True)),
                ('incidenciaHeridos', models.IntegerField(null=True)),
                ('incidenciaMuertos', models.IntegerField()),
            ],
        ),
    ]
