# Generated by Django 2.0.7 on 2018-07-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargoCod', models.CharField(max_length=10, unique=True)),
                ('cargoDescripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SubCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCargoCod', models.CharField(max_length=10, unique=True)),
                ('subCargoDescripcion', models.CharField(max_length=25)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargo.Cargo')),
            ],
        ),
    ]
